-- MySQL Script generated by MySQL Workbench
-- Thu Oct 16 15:15:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(80) NOT NULL,
  `middle_name` VARCHAR(80) NULL DEFAULT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `second_last_name` VARCHAR(80) NULL DEFAULT NULL,
  `email` VARCHAR(160) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `fk_users_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`auth_credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_credentials` (
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login_at` DATETIME NULL DEFAULT NULL,
  `password_updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_auth_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schools` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`course_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_categories` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `school_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`school_id` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_cc_school`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`schools` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `title` VARCHAR(160) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `teacher_id` BIGINT UNSIGNED NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `starts_at` DATETIME NULL DEFAULT NULL,
  `ends_at` DATETIME NULL DEFAULT NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_course_teacher` (`teacher_id` ASC) VISIBLE,
  INDEX `idx_course_category` (`category_id` ASC) VISIBLE,
  INDEX `fk_course_teacher` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_course_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`users` (`id`),
  CONSTRAINT `fk_course_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`course_categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`course_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_modules` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `position` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`course_id` ASC, `position` ASC) VISIBLE,
  INDEX `fk_cmodules_course` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_cmodules_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessons` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `module_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `content_url` VARCHAR(500) NULL DEFAULT NULL,
  `duration_minutes` INT UNSIGNED NULL DEFAULT NULL,
  `position` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`module_id` ASC, `position` ASC) VISIBLE,
  INDEX `fk_lessons_module` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `mydb`.`course_modules` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enrollments` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `enrolled_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('IN_PROGRESS', 'COMPLETED', 'WITHDRAWN') NOT NULL DEFAULT 'IN_PROGRESS',
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`student_id` ASC, `course_id` ASC) VISIBLE,
  INDEX `idx_enr_student` (`student_id` ASC) VISIBLE,
  INDEX `idx_enr_course` (`course_id` ASC) VISIBLE,
  INDEX `fk_enr_course` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_enr_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`users` (`id`),
  CONSTRAINT `fk_enr_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`course_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_progress` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `enrollment_id` BIGINT UNSIGNED NOT NULL,
  `percentage` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `last_update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`enrollment_id` ASC) VISIBLE,
  INDEX `fk_cprogress_enr` (`enrollment_id` ASC) VISIBLE,
  CONSTRAINT `fk_cprogress_enr`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `mydb`.`enrollments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`lesson_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson_progress` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `enrollment_id` BIGINT UNSIGNED NOT NULL,
  `lesson_id` BIGINT UNSIGNED NOT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`enrollment_id` ASC, `lesson_id` ASC) VISIBLE,
  INDEX `fk_lprog_lesson` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_lprog_enr`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `mydb`.`enrollments` (`id`),
  CONSTRAINT `fk_lprog_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lessons` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluations` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `lesson_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(160) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `due_at` DATETIME NULL DEFAULT NULL,
  `type` ENUM('QUIZ', 'TASK', 'EXAM') NOT NULL DEFAULT 'QUIZ',
  `pass_threshold` DECIMAL(5,4) NOT NULL DEFAULT 0.6000,
  `is_final_exam` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_eval_course` (`course_id` ASC) VISIBLE,
  INDEX `idx_eval_lesson` (`lesson_id` ASC) VISIBLE,
  INDEX `fk_eval_course` (`course_id` ASC) VISIBLE,
  INDEX `fk_eval_lesson` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_eval_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`),
  CONSTRAINT `fk_eval_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lessons` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `evaluation_id` BIGINT UNSIGNED NOT NULL,
  `prompt` TEXT NOT NULL,
  `type` ENUM('SINGLE', 'MULTI', 'OPEN') NOT NULL DEFAULT 'SINGLE',
  `points` DECIMAL(6,2) NOT NULL DEFAULT 1.00,
  `position` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`evaluation_id` ASC, `position` ASC) VISIBLE,
  INDEX `fk_q_eval` (`evaluation_id` ASC) VISIBLE,
  CONSTRAINT `fk_q_eval`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `mydb`.`evaluations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`options` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `question_id` BIGINT UNSIGNED NOT NULL,
  `text` TEXT NOT NULL,
  `is_correct` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_opt_q` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_opt_q`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`questions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attempts` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `evaluation_id` BIGINT UNSIGNED NOT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submitted_at` DATETIME NULL DEFAULT NULL,
  `score` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_att_eval_student` (`evaluation_id` ASC, `student_id` ASC) VISIBLE,
  INDEX `fk_att_eval` (`evaluation_id` ASC) VISIBLE,
  INDEX `fk_att_student` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_att_eval`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `mydb`.`evaluations` (`id`),
  CONSTRAINT `fk_att_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `attempt_id` BIGINT UNSIGNED NOT NULL,
  `question_id` BIGINT UNSIGNED NOT NULL,
  `option_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `open_text` TEXT NULL DEFAULT NULL,
  `is_correct` TINYINT(1) NULL DEFAULT NULL,
  `points_awarded` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ans_attempt` (`attempt_id` ASC) VISIBLE,
  INDEX `fk_ans_question` (`question_id` ASC) VISIBLE,
  INDEX `fk_ans_option` (`option_id` ASC) VISIBLE,
  CONSTRAINT `fk_ans_attempt`
    FOREIGN KEY (`attempt_id`)
    REFERENCES `mydb`.`attempts` (`id`),
  CONSTRAINT `fk_ans_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`questions` (`id`),
  CONSTRAINT `fk_ans_option`
    FOREIGN KEY (`option_id`)
    REFERENCES `mydb`.`options` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `storage_path` VARCHAR(500) NOT NULL,
  `size_bytes` BIGINT UNSIGNED NULL DEFAULT NULL,
  `checksum_sha256` CHAR(64) NULL DEFAULT NULL,
  `uploaded_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uploaded_by` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_media_course` (`course_id` ASC) VISIBLE,
  INDEX `fk_media_course` (`course_id` ASC) VISIBLE,
  INDEX `fk_media_uploader` (`uploaded_by` ASC) VISIBLE,
  CONSTRAINT `fk_media_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`),
  CONSTRAINT `fk_media_uploader`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`certificates` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `enrollment_id` BIGINT UNSIGNED NOT NULL,
  `pdf_path` VARCHAR(500) NOT NULL,
  `issued_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `verification_code` CHAR(16) NOT NULL,
  `grade_summary` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`verification_code` ASC) VISIBLE,
  INDEX `idx_cert_enr` (`enrollment_id` ASC) VISIBLE,
  INDEX `fk_cert_enr` (`enrollment_id` ASC) VISIBLE,
  CONSTRAINT `fk_cert_enr`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `mydb`.`enrollments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notifications` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `kind` ENUM('NEW_COURSE', 'EXAM', 'REMINDER', 'CERT_AVAILABLE') NOT NULL,
  `payload` JSON NULL DEFAULT NULL,
  `channel` ENUM('EMAIL') NOT NULL DEFAULT 'EMAIL',
  `status` ENUM('PENDING', 'SENT', 'ERROR') NOT NULL DEFAULT 'PENDING',
  `scheduled_at` DATETIME NULL DEFAULT NULL,
  `sent_at` DATETIME NULL DEFAULT NULL,
  `error_msg` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_notif_status` (`status` ASC, `scheduled_at` ASC) VISIBLE,
  INDEX `fk_notif_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notif_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
